<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.pkgmgr.available.js'); ?>
<div class="row">
  <div class="col-sm-9">
    <div class="panel panel-default">
      <div class="panel-heading"><span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span><?= $this->translate('List of available security fixes')?></div>
      <div class="panel-body">
	<?php echo $this->datatable('fixlist')->renderHtml(); ?>
      </div>
    </div>
  </div>
  <div class="col-sm-3" id="help">
    <h1><?=$this->translate('Help')?></h1>
    <blockquote id="help_legend">
      <p><?= $this->translate('You can click on the number of servers to have more details and patch all or part of these servers.')?></p>
    </blockquote>
  </div>
</div>
