<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <h2 class="modal-title"><?= $this->translate('Package Installation')?></h2>
</div>
<form class="form-horizontal" data-async action="<?php echo $this->url('package-manager-generic-patch', ['action' => 'patchHost','patch' => $patch ], [], true) ?>" method="POST">
  <input type="hidden" value="<?= $actionid ?>" name="actionid"/>
  <div class="modal-body">
      <div class="alert alert-<?= $divalert ?>"><?php if ($result['status'] === 'success'): ?>
          <?=  $this->translate('The following packages will be upgraded') ?>
          <?php else: ?>
          <?= $this->translate('Error with pre-patch on this server :') ?>
          <br/>
          <?= $result['errors'][$agent . '::' . $action][0]; ?>
          <?php endif ?>
      </div>
      <small>
      <?php if(isset($message)) :?>
          <strong>Note :</strong><br/>
          <?=  $message ?>
          <hr>
      <?php endif ?>
      </small>
      <?php if ($result['status'] === 'success'): ?>
      <div class="panel-group" id="patchTable" role="tablist" aria-multiselectable="true">
          <?php ksort($packages) ?>
          <?php foreach($packages as $hostname => $pkglist): ?>
          <div class="panel panel-default">
              <div class="panel-heading" role="tab" id="<?= str_replace('.','-',$hostname) ?>_patchTableHeading">
                  <h4 class="panel-title">
                      <a class="collapsed" data-toggle="collapse" data-parent="#patchTable" href="#<?= str_replace('.','-',$hostname) ?>_patchTableBody" aria-expanded="false" aria-controls="<?= str_replace('.','-',$hostname) ?>_patchTableBody">
     <?= $hostname ?> - <?= sprintf($this->translatePlural('%d package','%d packages', count($pkglist)),count($pkglist)) ?>
                      </a>
                  </h4>
              </div>
              <div id="<?= str_replace('.','-',$hostname) ?>_patchTableBody" class="panel-collapse collapse" role="tabpanel" aria-labelledby="<?= str_replace('.','-',$hostname) ?>_patchTableHeading">
                  <div class="panel-body">
                      <table class="table table-striped table-hover table-condensed bootstrap-datatable dataTable no-footer">
                          <thead>
	                      <tr>
	                          <th><?= $this->translate('Package') ?></th>
     	                          <th><?= $this->translate('From Version') ?></th>
	                          <th><?= $this->translate('To Version') ?></th>
	                          <th><?= $this->translate('Repository') ?></th>
	                      </tr>
                          </thead>
                          <tbody id="PackageListToUpgrade">
	                      <?php foreach($pkglist as $index => $package): ?>
	                      <tr><td><?= $package->package ?></td><td><?= $package->from_version ?><input type="hidden" value="<?= $package->from_version ?>" name="package[<?= $hostname ?>][<?= $package->package ?>][from_version]"/></td><td><?= $package->version ?><input type="hidden" value="<?= $package->version ?>" name="package[<?= $hostname ?>][<?= $package->package ?>][version]"/></td><td><?= $package->repo ?></td></tr>
	                      <?php endforeach ?>
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>
          <?php endforeach ?>
      </div>
  </div>
  <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
      <button type="submit" class="btn btn-primary"><?= $this->translate('Install Package') ?></button>
  </div>
  <?php  else: ?>
  <div class="modal-footer">
      <button type="button" class="btn btn-danger" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
  </div>
  <?php endif ?>
</form>
