<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <h2 class="modal-title"><?= $this->translate('Package Installation')?></h2>
</div>
<form class="form-horizontal" data-async action="<?php echo $this->url('package-manager-patch', ['action' => 'patchHost','server' => $host ], [], true) ?>" method="POST">
  <input type="hidden" value="<?= $actionid ?>" name="actionid"/>
  <div class="modal-body">
    <blockquote><?= $this->translate('The following packages will be upgraded') ?></blockquote>
    
    <table class="table table-striped table-hover table-condensed bootstrap-datatable dataTable no-footer">
      <thead>
	<th><?= $this->translate('Package') ?></th>
	<th><?= $this->translate('Version') ?></th>
	<th><?= $this->translate('Repository') ?></th>
      </thead>
      <tbody id="PackageListToUpgrade">
	<?php foreach($packages as $index => $package): ?>
	<tr><td><?= $package->package ?></td><td><?= $package->version ?><input type="hidden" value="<?= $package->version ?>" name="package[<?= $package->package ?>][version]"/></td><td><?= $package->repo ?></td></tr>
	<?php endforeach ?>
      </tbody>
    </table>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
    <button type="submit" class="btn btn-primary"><?= $this->translate('Install Package') ?></button>
  </div>
</form>
