<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.pkgmgr.show.js'); ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/kmb.pkgmgr.prepatchall.css'); ?>
<div class="panel">
    <div class="row">
        <div class="col-md-12">
            <div><strong><?php echo sprintf($this->translate('Details on patch %s'),$patch->getPublicId()) ?></strong></div>
        </div>
    </div>
    <div class="row">
      <div class="col-md-2 info-bar pull-left">
        <div>&nbsp;</div>
        <div class="stats-title"><a href="<?= $this->url('package-manager', [], [],true) ?>" class="btn btn-info"><i class="glyphicon glyphicon-chevron-left"></i> <?php echo $this->translate('back') ?></a></div>
      </div>
        <div class="pull-left col-md-5" >
            <!-- <p><?= sprintf($this->translatePlural('Affected package :<br/> <kbd>%s</kbd>', 'Affected package :<br/> <kbd>%s</kbd>', $patch->getPackages()), implode(', ',$patch->getPackages())) ?></p> -->
	</div>
        <div class="col-md-5 pull-right">
	  <div>&nbsp;</div>
	  <a id="patchAllBtn" class="btn btn-danger" type="button" data-url="<?= $this->url('package-manager-generic-prepatch',['patch' => $patch->getPublicId()],[],true) ?>"  <?= isset($environment) ? "" : "disabled"?>><?= $this->translate('Patch all hosts') ?></a>
	  <a target="_blank" type="button" class="btn btn-info" href="http://cve.mitre.org/cgi-bin/cvename.cgi?name=<?= $patch->getPublicId() ?>" ><?= $this->translate('Open CVE detail page ') ?></a>
	</div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
              <div class="panel-heading"><span class="glyphicon glyphicon-list-alt"></span><span class="panel-break"></span><?= $this->translate('Affected Hosts') ?></div>
	      <div class="panel-body">
		<table id="affectedhostlist" class="table table-striped table-hover table-condensed bootstrap-datatable dataTable no-footer">
		  <thead>
		    <th><?= $this->translate('Hostname')?></th>
		    <th><?= $this->translate('Action')?></th>
		  </thead>
		  <tbody>
              <?php foreach($patch->getAffectedHostsInContext() as $index => $host): ?>
		      <tr><td><?= $host ?></td><td><button class="btn btn-danger patch-btn" data-cve="<?= $patch->getPublicId() ?>" data-url="<?= $this->url('package-manager-generic-prepatch',['server' => $host],[],true) ?>" data-package="<?= implode(',',$patch->getPackages()) ?>"  <?= isset($environment) ? "" : "disabled"?>><?= $this->translate('Patch')?></button></td></tr>
		    <?php endforeach ?>
		  </tbody>
		</table>

		<div id="prepatch_detail" class="modal fade">
		  <div class="modal-dialog modal-lg">
		    <div class="modal-content" id="prepatch-modalcontent">
		    </div><!-- /.modal-content -->
		  </div><!-- /.modal-dialog -->
		  </div><!-- /.modal -->
                </div>
            </div>
        </div>
    </div>
</div>
